UPDATE "User"
SET "role" = CASE
    WHEN "role" = 'ADMIN' THEN 'ADMIN_FAMILIA'
    WHEN "role" = 'FAMILY' THEN 'FAMILIAR_LECTURA'
    WHEN "role" = 'CAREGIVER' THEN 'ENFERMERA'
    WHEN "role" = 'HOUSEKEEPING' THEN 'APOYO_DOMESTICO'
    ELSE "role"
END;

UPDATE "GroupMember"
SET "role" = CASE
    WHEN "role" = 'ADMIN' THEN 'ADMIN_FAMILIA'
    WHEN "role" = 'FAMILY' THEN 'FAMILIAR_LECTURA'
    WHEN "role" = 'CAREGIVER' THEN 'ENFERMERA'
    WHEN "role" = 'HOUSEKEEPING' THEN 'APOYO_DOMESTICO'
    ELSE "role"
END;
